# Generated by Django 4.2.4 on 2023-08-16 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('caso_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leyes.caso')),
            ],
        ),
    ]
