# Generated by Django 4.2.4 on 2023-08-16 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cliente_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leyes.cliente')),
            ],
        ),
    ]
