# Generated by Django 4.2.4 on 2023-08-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0003_abogado'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='edad',
            field=models.IntegerField(default=20, help_text='Ingrese su edad', verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='abogado',
            name='telefono',
            field=models.IntegerField(default=None, help_text='Ingrese su numero de telefono', verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='nombre',
            field=models.CharField(help_text='Ingrese su nombre', max_length=50, verbose_name='Nombre'),
        ),
    ]
