# Generated by Django 4.2.4 on 2023-08-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0004_abogado_edad_abogado_telefono_alter_abogado_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(default=18, help_text='Ingrese su edad', verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(default=None, help_text='Ingrese su numero de telefono', verbose_name='Celular'),
        ),
    ]
