# Generated by Django 4.2.4 on 2023-08-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0005_cliente_edad_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='ano',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='juzgado',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='caso',
            name='nro_expediente',
            field=models.IntegerField(default=0),
        ),
    ]
