# Generated by Django 4.2.4 on 2023-08-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0006_caso_ano_caso_juzgado_caso_nro_expediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='juzgado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
