# Generated by Django 4.2.4 on 2023-08-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0007_alter_caso_juzgado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='juzgado',
            field=models.CharField(default='Juzgado', max_length=100),
        ),
    ]
