# Generated by Django 4.2.4 on 2023-08-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0008_alter_caso_juzgado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caso',
            old_name='ano',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='caso',
            name='juzgado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
