# Generated by Django 4.2.4 on 2023-08-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0012_alter_caso_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='juzgado',
            field=models.CharField(default='Lugar', help_text='Ingrese el nombre del Juzgado', max_length=100),
        ),
        migrations.AlterField(
            model_name='caso',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del caso', max_length=40),
        ),
        migrations.AlterField(
            model_name='caso',
            name='nro_expediente',
            field=models.IntegerField(default=0, help_text='Ingrese en numero de expediente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text='Ingrese el numero del cliente', max_length=50),
        ),
    ]
