# Generated by Django 4.2.4 on 2023-08-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0015_caso_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_activo',
            field=models.BooleanField(default=False),
        ),
    ]
