# Generated by Django 4.2.4 on 2023-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0016_cliente_is_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
