# Generated by Django 4.2.4 on 2023-08-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0017_abogado_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
